steps:
  - name: ":hammer: Example Script"
    command: "./script.sh"
    artifact_paths: "artifacts/*"
    plugins:
      docker-compose#v2.5.1:
        run: bash
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

